/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RehabberRouteImport } from './routes/rehabber'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RequestResetPasswordRouteImport } from './routes/request-reset-password'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehabberRoute = RehabberRouteImport.update({
  id: '/rehabber',
  path: '/rehabber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestResetPasswordRoute = RequestResetPasswordRouteImport.update({
  id: '/request-reset-password',
  path: '/request-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rehabber': typeof RehabberRoute
  '/auth': typeof AuthRoute
  '/request-reset-password': typeof RequestResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rehabber': typeof RehabberRoute
  '/auth': typeof AuthRoute
  '/request-reset-password': typeof RequestResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rehabber': typeof RehabberRoute
  '/auth': typeof AuthRoute
  '/request-reset-password': typeof RequestResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rehabber' | '/auth' | '/request-reset-password' | '/update-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rehabber' | '/auth' | '/request-reset-password' | '/update-password'
  id: '__root__' | '/' | '/rehabber' | '/auth' | '/request-reset-password' | '/update-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RehabberRoute: typeof RehabberRoute
  AuthRoute: typeof AuthRoute
  RequestResetPasswordRoute: typeof RequestResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehabber': {
      id: '/rehabber'
      path: '/rehabber'
      fullPath: '/rehabber'
      preLoaderRoute: typeof RehabberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-reset-password': {
      id: '/request-reset-password'
      path: '/request-reset-password'
      fullPath: '/request-reset-password'
      preLoaderRoute: typeof RequestResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RehabberRoute: RehabberRoute,
  AuthRoute: AuthRoute,
  RequestResetPasswordRoute: RequestResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
